[tool.poetry]
name = "ollama-py"
version = "0.1.0"
description = ""
authors = ["prossima"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
fastapi = "0.115.5"
ollama = "0.3.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
